# ─────────────────────────────────────────────────────────────────────────────
#  공통(default) 설정
# * 별도의 spring.profiles 지정이 없으므로 항상 로드
# ─────────────────────────────────────────────────────────────────────────────

spring:
  application:
    name: boki-api

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
    disable-swagger-default-url: true
    path: /swagger-docs

logging:
  level:
    root: info
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security: debug
    com.boki.stresstest.aop: debug
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health
#  endpoint:
#    health:
#      show-components: always
#      show-details: always

encrypt:
  secret: Ym9raS1zcHJpbmcK
  salt: a30a397a58b723fb # openssl rand -hex 8

jwt:
  secret-key: eX3Q9v+N4k2uLx5Z8R0tYqV1bM3nC4pGd7sH6fJ1kL2m9bH0
  access-token-expiration: 1800             # 30 minutes
  refresh-token-expiration: 604800          # 1 week
  admin-access-token-expiration: 7776000    # 3 months
  admin-refresh-token-expiration: 31536000  # 1 year

---

# ─────────────────────────────────────────────────────────────────────────────
#  local 프로파일 전용 설정
# ─────────────────────────────────────────────────────────────────────────────
spring:
  config:
    activate:
      on-profile: default, local
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

  datasource:
    url: jdbc:h2:mem:stress_test
    username: sa
    password:
    driver-class-name: org.h2.Driver